version: 0.0
os: linux
files:
  - source: appspec.yml
    destination: /tmp
permissions:
  - object: /tmp/appspec.yml
    pattern: "**"
    owner: root
    group: root
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      runas: root
  DownloadBundle:
    - location: scripts/download_bundle.sh
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  Install:
    - location: scripts/install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      runas: root
